package verdict

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

// RenderJSON marshals the verdict as indented JSON.
func RenderJSON(w io.Writer, v Verdict) error {
	blob, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	_, err = w.Write(append(blob, '\n'))
	return err
}

// RenderText renders the compact form used by `ariadne verdict` (without
// --json): verdict word, counts, one line per reckless finding, next action.
// Capped at 15 lines.
func RenderText(w io.Writer, v Verdict) error {
	fmt.Fprintf(w, "VERDICT: %s — %s\n", strings.ToUpper(v.VerdictWord), countsSentence(v))
	for _, finding := range v.Reckless {
		fmt.Fprintf(w, "  %s  %s  (%s)\n", finding.ID, finding.Title, formatEvidenceLocation(finding.Where))
	}
	if v.Inconclusive > 0 {
		fmt.Fprintf(w, "Couldn't verify: %d path(s) lacked evidence — see ariadne ls cases.\n", v.Inconclusive)
	}
	fmt.Fprintf(w, "Next: %s\n", v.NextAction)
	return nil
}

// RenderReadout renders the one-screen template from docs/cli-contract.md.
// Hard cap: <=40 lines for <=3 reckless findings. Sections with zero entries
// are omitted, except that when the verdict is reckless, an empty
// TRADE-OFFS or HARDENED section prints a single "none observed" line.
func RenderReadout(w io.Writer, v Verdict) error {
	fmt.Fprintf(w, "Ariadne · AI agent risk readout\n")
	fmt.Fprintf(w, "Scanned %s · %d agent runtime(s) found (%s) · %d config file(s) read ·\n", v.Target, len(v.Scanned.Runtimes), strings.Join(v.Scanned.Runtimes, ", "), v.Scanned.Surfaces)
	fmt.Fprintf(w, "nothing executed, no secret values read\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "  VERDICT: %s — %s.\n", strings.ToUpper(v.VerdictWord), countsSentence(v))
	fmt.Fprintf(w, "\n")

	reckless := v.VerdictWord == WordReckless

	if len(v.Reckless) > 0 {
		fmt.Fprintf(w, "  RECKLESS ── fix these ──\n")
		for _, finding := range v.Reckless {
			fmt.Fprintf(w, "  %d. %s\n", recklessNumber(finding.ID), finding.Title)
			fmt.Fprintf(w, "       where  %s\n", formatEvidenceLocation(finding.Where))
			fmt.Fprintf(w, "       why    %s\n", finding.Why)
			fmt.Fprintf(w, "       fix    %s\n", finding.Fix)
		}
		fmt.Fprintf(w, "\n")
	}

	if len(v.Tradeoffs) > 0 {
		fmt.Fprintf(w, "  TRADE-OFFS ── normal cost of using agents ──\n")
		for _, t := range firstTradeoffs(v.Tradeoffs, 5) {
			fmt.Fprintf(w, "  •  %s\n", t.Summary)
		}
		fmt.Fprintf(w, "\n")
	} else if reckless {
		fmt.Fprintf(w, "  TRADE-OFFS ── none observed ──\n")
		fmt.Fprintf(w, "\n")
	}

	if len(v.Hardened) > 0 {
		fmt.Fprintf(w, "  HARDENED ── working in your favor ──\n")
		for _, h := range firstHardened(v.Hardened, 6) {
			fmt.Fprintf(w, "  ✓  %s (enforced) — %s\n", h.Summary, h.Source)
		}
		fmt.Fprintf(w, "\n")
	} else if reckless {
		fmt.Fprintf(w, "  HARDENED ── none observed ──\n")
		fmt.Fprintf(w, "\n")
	}

	if v.Inconclusive > 0 {
		fmt.Fprintf(w, "  Couldn't verify: %d path(s) lacked evidence — see ariadne ls cases.\n", v.Inconclusive)
	}

	fmt.Fprintf(w, "  Next: %s\n", v.NextAction)
	fmt.Fprintf(w, "  More: ariadne show %s · ariadne ls findings · --format json\n", moreShowTarget(v))
	return nil
}

func formatEvidenceLocation(loc EvidenceLocation) string {
	if loc.Source == "" {
		return ""
	}
	if loc.Line > 0 {
		return fmt.Sprintf("%s:%d", loc.Source, loc.Line)
	}
	return loc.Source
}

func moreShowTarget(v Verdict) string {
	if len(v.Reckless) > 0 {
		return v.Reckless[0].ID
	}
	if len(v.Hardened) > 0 {
		return v.Hardened[0].ID
	}
	return "reckless:1"
}

func firstTradeoffs(in []TradeoffLine, limit int) []TradeoffLine {
	if len(in) <= limit {
		return in
	}
	return in[:limit]
}

func firstHardened(in []HardenedLine, limit int) []HardenedLine {
	if len(in) <= limit {
		return in
	}
	return in[:limit]
}

// recklessNumber extracts the screen number from a "reckless:N" id. Falls
// back to 0 (rendered as "0.") if the id is not in the expected shape; this
// should never happen since IDs are generated by Build.
func recklessNumber(id string) int {
	n := 0
	for _, r := range id {
		if r < '0' || r > '9' {
			continue
		}
		n = n*10 + int(r-'0')
	}
	return n
}

func countsSentence(v Verdict) string {
	if v.VerdictWord == WordNoAgentsFound {
		if len(v.Hardened) > 0 {
			return fmt.Sprintf("no agent runtimes found · %d enforced control(s) present", len(v.Hardened))
		}
		return "no agent runtimes found"
	}
	parts := make([]string, 0, 3)
	if len(v.Reckless) > 0 {
		parts = append(parts, fmt.Sprintf("%d finding(s) need action", len(v.Reckless)))
	}
	if len(v.Tradeoffs) > 0 {
		parts = append(parts, fmt.Sprintf("%d trade-off(s) you're accepting", len(v.Tradeoffs)))
	}
	if len(v.Hardened) > 0 {
		parts = append(parts, fmt.Sprintf("%d control(s) working for you", len(v.Hardened)))
	}
	if len(parts) == 0 && len(v.Scanned.Runtimes) > 0 {
		return fmt.Sprintf("%d agent runtime(s) found", len(v.Scanned.Runtimes))
	}
	return strings.Join(parts, ", ")
}
